options(digits = 8, scipen = 9999)
library(plyr)
library(dplyr)
library(tibble)
library(tidyr)
library(survival)
library(cmprsk)
library(tictoc)
library(DescTools)
library(pROC)
library(flexsurv)
library(CFC)
library(InformationValue)
library(purrr)
library(ggplot2)
library(viridis)
library(hrbrthemes)
library(pec)
library(prodlim)
library(riskRegression)
library(rms)
library(iCARE)
library(pROC)
library(cutpointr)
library(nnet)
library(PropCIs)
library(matrixStats)
#library(RemixAutoML)
library(reportROC)
library(mice)
library(rms)
library(DescTools)
library(ROCit)
library(cutpointr)
library(Rcpp)
reqPcks <- c("doSNOW", "mexhaz","Matrix","ggplot2", "plyr", "gridExtra","survival")
for(p in reqPcks){
  if(!require(p, character.only=TRUE)){
    install.packages(p)
    library(p, character.only = TRUE)}}
library(lemon)
library(knitr)

#library(kableExtra)
#library(gdata)
#library(timereg)
#library(plotrix)
#library(memisc)
#library(scales)
#library(latex2exp)
#library(mice)